- name: restart chronyd
  systemd:
    state: restarted
    daemon_reload: yes
    name: chronyd
    enabled: yes
  become: yes

- name: restart firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld
    enabled: yes
  become: yes

- name: restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld
    enabled: yes
  listen: "restart firewalld"
  become: yes
