---
- hosts: all
  gather_facts: True
  gather_subset: [network, hardware]
  roles:
    - standard-node

# - hosts: rancher_load_balancer
#   roles:
#     - rancher-load-balancer

- hosts: rancher
  gather_facts: True
  gather_subset: [network, hardware]
  roles:
    - rancher-node
