- name: "download and replace helm {{ helm_version }}"
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - "--strip=1"
      - --wildcards
      - "*/helm"
  become: yes
